import type { Metadata } from 'next'
import { Inter, Cedarville_Cursive } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import mybg from '@/public/home-background.png'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Charandeep | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen max-w-screen-2xl bg-cover relative ${inter.className}`}>
        <Image src={mybg} alt='bg' fill className='z-[-99]' priority />
        {children}
      </body>
    </html>
  )
}
